resources:
  - name: mySecret
    type: integration
    integration: drship_jf_docker # Replace with the name you created in the earlier step

jobs:
  - name: prod_deploy
    type: runSh
    steps:
      - IN: mySecret   # Specify the resource as an IN
      - TASK:
          name: first_task   
          script:
            - MY_USERNAME=$(shipctl get_integration_resource_field "mySecret" "username") # Retrieve username
            - echo $MY_USERNAME          



         
